#include "selection_metrics.h"
#include "selection_metrics_builder.h"

SelectionMetrics::SelectionMetrics(const SelectionMetricsBuilder& builder)
    : team_id(builder.get_team_id()),
      generation(builder.get_generation()),
      best_fitness(builder.get_best_fitness()),
      validation_fitness(builder.get_validation_fitness()),
      team_size(builder.get_team_size()),
      age(builder.get_age()),
      fitness_value_for_selection(builder.get_fitness_value_for_selection()),
      program_instruction_count(builder.get_total_program_instructions()),
      effective_program_instruction_count(builder.get_total_effective_program_instructions()),
      best_agent_register_size(builder.get_best_agent_register_size()),
      best_agent_effective_register_size(builder.get_best_agent_effective_register_size()),
      best_agent_flops(builder.get_best_agent_flops()),
      elite_avg_start_rate_swap(builder.get_elite_avg_start_rate_swap()),
      elite_avg_start_rate_delete(builder.get_elite_avg_start_rate_delete()),
      elite_avg_start_rate_add(builder.get_elite_avg_start_rate_add()),
      elite_avg_start_rate_mutate(builder.get_elite_avg_start_rate_mutate()),
      elite_avg_start_rate_s5(builder.get_elite_avg_start_rate_s5()),
      elite_avg_output_rate_swap(builder.get_elite_avg_output_rate_swap()),
      elite_avg_output_rate_delete(builder.get_elite_avg_output_rate_delete()),
      elite_avg_output_rate_add(builder.get_elite_avg_output_rate_add()),
      elite_avg_output_rate_mutate(builder.get_elite_avg_output_rate_mutate()),
      elite_avg_output_rate_s5(builder.get_elite_avg_output_rate_s5()),
      operations_use(builder.get_operations_use()),
      pareto_front_0_size(builder.get_pareto_front_0_size()),
      pareto_front_1_size(builder.get_pareto_front_1_size()),
      best_agent_pareto_rank(builder.get_best_agent_pareto_rank()),
      best_agent_crowding_dist(builder.get_best_agent_crowding_dist()),
      avg_complexity_front_0(builder.get_avg_complexity_front_0()),
      best_agent_mean_register_similarity(builder.get_best_agent_mean_register_similarity()),
      best_agent_max_register_similarity(builder.get_best_agent_max_register_similarity()),
      validation_register_efficiency_pearson(builder.get_validation_register_efficiency_pearson()),
      validation_register_efficiency_spearman(builder.get_validation_register_efficiency_spearman()),
      validation_register_efficiency_n(builder.get_validation_register_efficiency_n()) {
}
